### PR TITLE
Add markdown support

### PR DESCRIPTION
**Pull request by grumpyoldman-io**
Heya,

I've created a `asMarkdown` function based on the `asHTML`. You also see a lot of code formatting here, I think this is because of the lack of linters (I only used prettier here).

The tests are updated, and so is the readme.

let me know what you think.

aside:
- embed and label are not supported by MD.

### CODE REVIEW

**Comment by arnaudlewis** [comment]
Hi @grumpyoldman-io, I really appreciate your PR and it seems pretty good.
One thing, I'd rather do it in another library, something like prismic-markdown which handles markdown and only that.
I think it makes more sense to split in different libraries according to the format we want.
For instance we have Prismic-dom for html, prismic-reactjs for react component and so on.
What do you think?

**Comment by grumpyoldman-io** [comment]
Hey @arnaudlewis, yeah, that would be a lot better I guess. How do you want to handle this? I can image that you prefer that Prismic would be the owner of that package. You are welcome to copy/paste my code if you like (it's basicly what I did). I can also push my code to the new package if you like.

**Comment by arnaudlewis** [comment]
All right then we'll do it that way.
Thank you for your contribution :)

Le mar. 26 févr. 2019 à 11:33, Marvin de Bruin <notifications@github.com> a
écrit :

**Comment by grumpyoldman-io** [comment]
@arnaudlewis Can you post an update when it is available here? Or if you need help.

**Comment by arnaudlewis** [comment]
No problem

Le mar. 26 févr. 2019 à 14:07, Marvin de Bruin <notifications@github.com> a
écrit :

**Comment by grumpyoldman-io** [comment]
@arnaudlewis I've created a repo since I need it on a project I'm working on. I've invited you as a collaborator. It is not yet available as a NPM module, I've just set up the codebase based on prismic-dom/reactjs

**Comment by grumpyoldman-io** [comment]
@arnaudlewis I've published the package https://www.npmjs.com/package/prismic-markdown. Feel free to email me to transfer ownership or for collaboration.

**Pull request closed without merging**
