### PR TITLE
Update prismic-richtext to reduce bundle size

### LINKED ISSUE #35: 90.1 KB minified?
This script clocks in at a massive 90.1 KB minified.

For context:
- [marked](https://github.com/markedjs/marked), a full blown Markdown parser, is 23.2 KB minified
- React + React DOM is ~106 KB

How is it possible for this to be so positively colossal?

We need to be able to get RichText in a different format like `markdown`, or plain `HTML` **straight from the Prismic API**, or reduce the size of this dependency **tenfold** for it to be usable client-side.

### PR DESCRIPTION
**Pull request by controversial**
Closes #35

### CODE REVIEW

**Comment by hypervillain** [comment]
Thank you for this! I believe it's also time to bump the node versions that Travis checks for. Could update the `travis.yml` file?

Values to handle are probably 8, 10 and 12.

thanks!

**Comment by controversial** [comment]
@hypervillain I updated the node versions in `.travis.yml` to the ones you specified. Webpack v2 doesn't support node versions after 9.x, so I also updated the `package.json` and `webpack.config.js` to webpack v4, but that update should definitely get a second pair of eyes.

It look like the tests are still failing because of broken test cases—there are some test cases that expect `<em><strong></strong</em>` while `prismic-dom` is generating the equivalent `<strong><em></em></strong>` (order is reversed). Let me know how we should proceed.

**Comment by hypervillain** [comment]
@controversial The tests were indeed failing on non v12 node versions. Because they're actually quite old and not really relevant, I thought the best choice was to actually remove them from the codebase. I juste merged your code with the deletion.

I don't have the rights to publish unfortunately. @arnaudlewis can you do it asap?

**Comment by simonmaass** [comment]
can this please be released... please...

**Pull request merged**
